Contact form
medijdir/mobileportfolio pull request #3
Opened 2023-07-12 11:57 UTC by medijdir

## Highlights 🌟
in this project I have used: 
✔️ Form propriety 
✔️ HTML 
✔️  Use CSS flex to place elements on the page.
✔️  GitHub flow

2023-07-12 12:32 UTC, muneebulrehman requested changes
Hi @medijdir , 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- No linter errors
- Descriptive PR
- Great job adding the form to your application.

## Required Changes ♻️
_Check the comments under the review._

- [ ] I see your partner made a commit. However, it is not a meaningful contribution to the project. Please ask your partner to contribute to the code base. You can let him fix the design for instance.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-12 12:32 UTC, muneebulrehman commented on index.html
> +        <section class="contact_form">
As per the Figma template provided to you, there is a certain gap between the `Skills` section and `Contact` section. However, in your design, there is no such gap. Kindly add some margin between the two. 

| Your design  | Figma design |
| ------------- | ------------- |
| ![image](https://github.com/medijdir/mobileportfolio/assets/33268927/1ccfcab8-851d-4b27-ad2b-44d03b9685f1) | ![image](https://github.com/medijdir/mobileportfolio/assets/33268927/f323d442-2c87-4ec4-afa7-01c7214dfd0e) |

2023-07-13 07:44 UTC, souad988 requested changes
Hi @medijdir  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
Great efforts
Use of semantic html tags
Correct use of form action property 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-13 07:44 UTC, souad988 commented on index.html
> +        <section class="contact_form">
Kindly as requested by the previous reviewer fix the spacing issue between the about and contact sections , you can solve this problem in many ways and I suggest that you avoid setting fixed height for your components the good practice is to use padding and margin properties and let your content size reserve the height from dom flow , add padding-Bottom to the about section and for the color behind the contact form you can add subContainer to this section with properties of contact section and set contact section color to be white , feel free to use other solutions but  please make sure your project looks like the template before re-requesting review .

![image (22)](https://github.com/medijdir/mobileportfolio/assets/59707859/f625f21f-c14e-4eb9-9106-839b6e06773f)

2023-07-13 10:42 UTC, muneebulrehman approved these changes
Hi @medijdir , 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥳
Congratulations! 🎉 

# Status: Approved✔️

## Highlights
- No linter errors
- Descriptive PR
- Good follow-up with the previous reviewer
- Good job with the design.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-13 10:42 UTC, muneebulrehman commented on style.css
> +  height: 72rem;
- Optional
Setting a fixed height in such a scenario is never a good idea. You can consider using `margin-bottom` on this section or `margin-top` on the Contact section to put some distance between the two.

2023-07-13 11:51 UTC, merged